project:
  type: book
  output-dir: docs

book:
  title: "私たちの{cmdstanr}"
  subtitle: 'ベイズ統計学への道'
  sidebar:
    style: 'docked'
    search: true
  chapters:
    - index.qmd
    - part: ベイズ統計学とは
      chapters:
        - StatisticsBasic.qmd
    - part: RとStanついて
      chapters: 
        - RBasic.qmd
        - StanBasic.qmd
    - part: 実践編
      chapters:
        - Practice.qmd
    - part: 付録
      chapters: 
        - Appendix.qmd
  page-footer:
    center: 'Copyright 2024, YY Laboratory'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 375px

